[project]
name = "smarthired"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.12",
    "google-genai>=1.20.0",
    "pyyaml>=6.0.2",
    "streamlit>=1.45.1",
]
